(function(){
'use strict';
const G=window.Koushou2, IMG=window.KOUSHO_ASSETS, $=id=>document.getElementById(id);
let state=null,mode='welcome',saved=null,storageOK=true,modalReturn=null,dialogReturn=null,toastTimer=null,completed=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n.toLocaleString('ja-JP')+' Cr';
function load(){try{const raw=localStorage.getItem(G.SAVE_KEY);if(raw){const v=JSON.parse(raw);if(G.valid(v))saved=v;else $('saveNotice').textContent='途中記録を読めませんでした。新しく始められます。第一章の記録には影響しません。';}const c=JSON.parse(localStorage.getItem('kitsune_w02_endings')||'[]');if(Array.isArray(c))completed=c.filter(x=>Object.hasOwn(G.ENDINGS,x));}catch(e){storageOK=e.name==='SyntaxError';$('saveNotice').textContent=storageOK?'途中記録を読めませんでした。新しく始められます。第一章の記録には影響しません。':'この環境では記録を保存できません。このページを開いたまま遊んでください。';}}
function save(){if(!state)return;try{localStorage.setItem(G.SAVE_KEY,JSON.stringify(state));saved=JSON.parse(JSON.stringify(state));if(state.end&&!completed.includes(state.end)){completed.push(state.end);localStorage.setItem('kitsune_w02_endings',JSON.stringify(completed));}storageOK=true;}catch(e){if(storageOK)toast('途中記録を保存できません。ページを閉じると、この章の進行が失われることがあります。');storageOK=false;}}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000);}
function apply(result){if(result.error){toast(result.error);return;}state=result.state;save();render();}
function showWelcome(){mode='welcome';$('welcome').hidden=false;$('game').hidden=true;$('ending').hidden=true;$('dialogLayer').hidden=true;closeModal();$('resume').hidden=!saved;$('resume').textContent=saved&&saved.end?'第二章の航海日誌を見る':'第二章をつづける';$('start').textContent=saved?'第二章をはじめから':'第二章をはじめる';if(saved&&storageOK)$('saveNotice').textContent=saved.end?'記録：'+G.ENDINGS[saved.end].name:'記録：'+G.LOCATIONS[saved.loc].name+' / '+G.time(saved.t)+' / '+money(saved.money);}
function start(){state=G.fresh();mode='game';save();render();}
function resume(){state=JSON.parse(JSON.stringify(saved));mode='game';render();}
function openModal(title,html){modalReturn=document.activeElement;$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modalLayer').hidden=false;for(const id of ['welcome','game','ending'])$(id).inert=true;$('closeModal').focus();}
function closeModal(){const open=!$('modalLayer').hidden;$('modalLayer').hidden=true;for(const id of ['welcome','game','ending'])$(id).inert=!!(state&&state.dialog&&mode==='game');if(open&&modalReturn&&modalReturn.isConnected)modalReturn.focus();}
function button(label,fn,cls=''){const b=document.createElement('button');b.type='button';b.className=cls;b.innerHTML=label;b.onclick=fn;return b;}
function stageArt(loc){const colors={office:['#162735','#263c42'],berth:['#111c32','#293543'],depot:['#28212c','#4b3632'],ship:['#152a30','#26383b']};const c=colors[loc];return '<svg viewBox="0 0 900 360" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><defs><linearGradient id="sky2" x2="0" y2="1"><stop stop-color="'+c[0]+'"/><stop offset="1" stop-color="'+c[1]+'"/></linearGradient></defs><rect width="900" height="360" fill="url(#sky2)"/>'+Array.from({length:18},(_,i)=>'<circle cx="'+((i*137+39)%900)+'" cy="'+((i*43+20)%180)+'" r="'+(i%2?1:1.7)+'" fill="#c9dce8" opacity=".4"/>').join('')+'<path d="M0 240H900V360H0Z" fill="#0e1521"/><path d="M0 245H900 M0 290H900 M0 335H900" stroke="#a9a28a" opacity=".16"/>'+Array.from({length:8},(_,i)=>'<path d="M'+(450+(i-4)*70)+' 240L'+(450+(i-4)*220)+' 360" stroke="#c9a25a" opacity=".1"/>').join('')+'<path d="M420 225V100H800V225 M460 100V55H740V100" fill="none" stroke="#829490" stroke-width="7" opacity=".25"/><path d="M515 216Q490 171 538 150L740 160Q815 170 830 220Z" fill="#222c39" stroke="#617077" stroke-width="2"/><path d="M550 179L714 184" stroke="#c9a25a" opacity=".5"/><g fill="#6fd0c8" opacity=".65"><rect x="582" y="179" width="13" height="9"/><rect x="607" y="180" width="13" height="9"/><rect x="632" y="181" width="13" height="9"/></g><path d="M40 245V155H175V245 M65 155V129H152V155" fill="#151c29" stroke="#c9a25a" stroke-width="2" opacity=".55"/><path d="M70 184H147M70 201H132" stroke="#e4743c" opacity=".7"/><text x="65" y="234" fill="#c9a25a" font-family="monospace" font-size="15" opacity=".7">02 / AMANA</text></svg>';}
function render(){
 $('welcome').hidden=true;$('game').hidden=!!(state.end&&!state.dialog);$('ending').hidden=!state.end||!!state.dialog;
 $('clock').textContent=G.time(state.t);$('money').textContent=money(state.money);
 const late=state.t>=7;let warn='';if(state.t>=12)warn='保守便の準備期限は12時。今便に間に合う出航は18時までです。';else if(state.t>=8)warn='10時枠の変更登録は9時まで。移動と手続きの時間も必要です。';else if(late)warn='臨時便の手配期限は7時。早い枠の交換は9時までに登録してください。';if(!storageOK)warn='保存できていません。ページを閉じずに遊んでください。 '+warn;$('warning').hidden=!warn;$('warning').textContent=warn;
 const loc=G.LOCATIONS[state.loc];$('locationName').textContent=loc.name;$('locationDetail').textContent=loc.detail;$('stageArt').innerHTML=stageArt(state.loc);
 $('locations').replaceChildren();for(const [id,l]of Object.entries(G.LOCATIONS)){const b=button(esc(l.name),()=>apply(G.move(state,id)));b.setAttribute('aria-current',id===state.loc?'true':'false');b.disabled=id===state.loc||!!state.dialog||!!state.end;$('locations').append(b);}
 $('actions').replaceChildren();for(const a of G.availableActions(state)){const b=button('<span>'+esc(a.label)+'</span><small>'+(a.done&&!a.repeat?'確認済み':a.cost?'30分':'無料')+'</small>',()=>apply(G.act(state,a.id)));b.disabled=(a.done&&!a.repeat)||!!state.dialog||!!state.end;$('actions').append(b);}
 if(state.loc==='berth'&&G.has(state,'need')&&!G.has(state,'agreement'))$('actions').append(button('交換する条件を考える',proposalModal,'special'));
 if(state.loc==='office'&&G.has(state,'agreement')&&!G.has(state,'registered'))$('actions').append(button('合意を港に登録する <small>30分・1,000 Cr</small>',()=>confirmRegistration(),'special'));
 if(state.loc==='depot'&&G.has(state,'service')&&!G.has(state,'delivery')&&!G.has(state,'registered'))$('actions').append(button('運ぶ荷物を相談する',deliveryModal,'special'));
 if(G.has(state,'agreement')&&!G.has(state,'registered'))$('actions').append(button('予約票だけで出航できるか確かめる <small>30分</small>',()=>apply(G.informal(state))));
 $('promise').textContent=G.has(state,'registered')?(state.flags.protected?'10時の枠へ登録済み。荷渡しが18時を過ぎたら相手は23時枠へ。夜間費用の負担は500 Cr。':'10時の枠へ登録済み。荷物が遅れた場合の費用は、相手側に残っている。'):G.has(state,'agreement')?'船長の同意あり。まだ港に登録していないため、出航予約は変わっていない。':G.has(state,'delivery')?'電池1.2tの運搬を受託済み。12時までに決め、14時の保守便で出航する。':'本船の予約は20時。翌朝の船団に間に合う方法を探している。';
 $('routes').replaceChildren();let n=0;for(const [id,r]of Object.entries(G.ROUTES)){if(!r.known(state))continue;n++;const el=document.createElement('div');el.className='route-card';const why=r.why(state);el.innerHTML='<h3>'+esc(r.title)+'</h3><p>'+esc(r.summary)+'</p><p class="route-price">'+(id==='swap'?'登録済み':money(r.price))+' / '+G.time(r.depart)+'</p><p>'+esc(why||r.trade)+'</p>';const b=button('条件を確認',()=>preview(id));b.disabled=!!why||!!state.dialog||!!state.end;el.append(b);$('routes').append(el);}$('routeCount').textContent=n+'通り';
 if(state.dialog){if($('dialogLayer').hidden)dialogReturn=document.activeElement;const d=state.dialog,l=d.lines[d.index],c=G.CREW[l.who];$('dialogLayer').hidden=false;$('speaker').textContent=c.name||'航海日誌';$('dialogText').textContent=l.text;$('dialogProgress').textContent=(d.index+1)+' / '+d.lines.length;$('portrait').className='portrait'+(l.who==='n'?' empty':'');$('portrait').innerHTML=c.face?'<img src="'+IMG[c.face]+'" alt="">':esc(c.name?c.name.slice(0,2):'');$('next').textContent=d.index===d.lines.length-1?'読み終える':'つづきへ ▼';$('next').focus();$('game').inert=true;$('ending').inert=true;}
 else{$('dialogLayer').hidden=true;$('game').inert=false;$('ending').inert=false;if(state.end)renderEnding();else if(dialogReturn&&dialogReturn.isConnected){dialogReturn.focus();dialogReturn=null;}}
}
function proposalModal(){const p=state.proposal;openModal('船長に提示する条件','<p>早い出航枠を受け取る代わりに、何を渡し、何を確かめて約束するか。</p><label class="form-field"><span>こちらが差し出すもの</span><select id="give"><option value="slot">自船の20時の出航枠</option><option value="cash">2,000 Crを払う</option><option value="nothing">早い枠だけ譲ってもらう</option></select></label><label class="form-field"><span>時刻の根拠</span><select id="evidence"><option value="unknown">荷物は間に合うと思う</option><option value="arrival">入港見込み14時を根拠にする</option><option value="verified">荷渡しと積込の記録を示す'+(G.has(state,'release')?'':'（未確認）')+'</option></select></label><label class="form-field"><span>追加検査で遅れたとき</span><select id="delay"><option value="none">まだ条件を決めない</option><option value="shared">23時の予備枠、夜間費用を500ずつ'+(G.has(state,'lateSlot')?'':'（港へ未確認）')+'</option></select></label><p class="small">提案には30分。合意しただけでは出航予約は変わりません。</p><div class="buttons"><button id="submitProposal" class="primary">この条件で話す</button></div>');for(const key of ['give','evidence','delay']){$(key).value=p[key];$(key).onchange=()=>{state=G.setProposal(state,key,$(key).value);save();};}$('submitProposal').onclick=()=>{closeModal();apply(G.propose(state));};}
function confirmRegistration(){openModal('予約変更を登録する','<dl class="terms"><dt>本船</dt><dd>20時 → 10時</dd><dt>オルド</dt><dd>10時 → 20時</dd><dt>手数料</dt><dd>1,000 Cr</dd><dt>所要時間</dt><dd>30分。9時までに登録完了</dd><dt>遅延時</dt><dd>'+esc(state.flags.protected?'23時の予備枠へ。夜間費用は500 Crずつ。':'追加費用は相手が負担。予備枠の保証なし。')+'</dd></dl><p>登録すると、本船の20時枠は相手に移ります。</p><div class="buttons"><button id="registerConfirm" class="primary">登録する</button></div>');$('registerConfirm').onclick=()=>{closeModal();apply(G.registration(state));};}
function deliveryModal(){openModal('引き受ける荷物を決める','<p>港の保守便は14時発。荷主の条件と、本船の安全な積載量を合わせて考える。</p><div class="fact"><strong>本船の積載量</strong><p>'+esc(G.has(state,'capacity')?G.FACTS.capacity.text:'まだ実物を確認していない。')+'</p></div><div class="fact"><strong>荷物と納期</strong><p>'+esc(G.has(state,'manifest')?G.FACTS.manifest.text:'まとめた荷物は2.4t。内訳と納期はまだ確認していない。')+'</p></div><p class="small">相談は30分。受託期限12時。荷物が載らない場合は、その場で断れる。</p><div class="buttons"><button id="allCargo">2.4tすべてを提案</button><button id="splitCargo" class="primary">電池1.2tだけを提案</button></div>');$('allCargo').onclick=()=>{closeModal();apply(G.takeDelivery(state,false));};$('splitCargo').onclick=()=>{closeModal();apply(G.takeDelivery(state,true));};}
function preview(id){const r=G.ROUTES[id],cost=r.price+(id==='swap'&&state.flags.protected?500:0);openModal('この航路で決める？','<h3>'+esc(r.title)+'</h3><dl class="terms"><dt>出航</dt><dd>'+G.time(r.depart)+'</dd><dt>ここからの費用</dt><dd>'+money(r.price)+(id==='swap'&&state.flags.protected?' ＋ 遅延時500 Cr':'')+'</dd><dt>残る予算</dt><dd>'+money(state.money-r.price)+(id==='swap'&&state.flags.protected?'（遅延時 '+money(state.money-cost)+'）':'')+'</dd><dt>条件</dt><dd>'+esc(r.trade)+'</dd></dl>'+(id==='wait'?'<p>今便には合流しません。2日後の船団を待ちます。</p>':'')+(id==='swap'&&!state.flags.protected?'<p>荷渡しが遅れる可能性は残っています。相手の追加費用や代替枠は決めていません。</p>':'')+(G.has(state,'delivery')&&id!=='delivery'?'<p>受託した運搬依頼は、出航前に辞退を伝えます。まだ積載前なので取消費用はありません。</p>':'')+(G.has(state,'agreement')&&!G.has(state,'registered')&&id!=='swap'?'<p>未登録の交換案は、船長に見送りの連絡をして確認します。</p>':'')+'<div class="buttons"><button id="commitRoute" class="primary">この航路で出航する</button><button id="cancelRoute">まだ考える</button></div>');$('cancelRoute').onclick=closeModal;$('commitRoute').onclick=()=>{closeModal();apply(G.choose(state,id));};}
function journal(){openModal('ききこみ帳','<p class="small">確かめたこと '+state.facts.length+'件。書類で確認できない未来の出来事は、未確定のまま残す。</p>'+state.facts.map(k=>'<div class="fact"><strong>'+esc(G.FACTS[k].title)+'</strong><p>'+esc(G.FACTS[k].text)+'</p></div>').join('')+'<h3>行動の記録</h3><ol class="log-list">'+state.log.map(l=>'<li>'+G.time(l.t)+' '+esc(l.text)+'</li>').join('')+'</ol>');}
function renderEnding(){const E=G.ENDINGS[state.end];$('ending').innerHTML='<p class="eyebrow">航海日誌　/　WORLD 02 関門港アマナ</p><h1>'+esc(E.name)+'</h1><p class="subtitle">'+esc(E.subtitle)+'</p><div class="end-stats"><div class="end-stat"><span>出航 / 記録時刻</span><b>'+G.time(state.t)+'</b></div><div class="end-stat"><span>寄港予算の残り</span><b>'+money(state.money)+'</b></div><div class="end-stat"><span>約束の結果</span><b>'+esc(E.relation)+'</b></div></div><p class="end-note">'+esc(E.note)+'</p><details><summary>今回の行動を振り返る</summary><ol class="log-list">'+state.log.map(l=>'<li>'+G.time(l.t)+' '+esc(l.text)+'</li>').join('')+'</ol></details><p class="small" style="color:#6b5640">このブラウザーで見た第二章の結末 '+completed.length+' / '+Object.keys(G.ENDINGS).length+'</p><div class="buttons"><button id="again" class="primary">別の条件で、もう一度</button><a class="button secondary" href="index.html">第一章へ</a><button id="toChapterTitle" class="secondary">第二章のタイトルへ</button></div><p class="footer-note">登場人物のモデル：<a href="https://tales.note.com/ai_neko_namake/wwqir8bbskobr" target="_blank" rel="noopener">宇宙船日誌 番外編</a>。関門港アマナ、港の人々と今回の出来事はゲーム独自のエピソードです。</p>';$('again').onclick=()=>restart();$('toChapterTitle').onclick=showWelcome;}
function restart(){openModal('第二章をはじめから','<p>この章の途中経過を、新しい航路の記録に置き換えます。見た結末の記録と第一章のコレクションは残ります。</p><div class="buttons"><button id="restartConfirm" class="primary">はじめから遊ぶ</button><button id="restartCancel">もどる</button></div>');$('restartConfirm').onclick=()=>{closeModal();start();};$('restartCancel').onclick=closeModal;}
function menu(){openModal('章のメニュー','<p>途中経過は行動ごとに保存されています。</p><div class="buttons"><button id="chapterTitle">第二章のタイトルへ</button><button id="restartMenu">はじめから</button></div><h3>この章について</h3><p>原作の人物をモデルにした、後日の再会と寄港を描くゲーム独自のエピソードです。最初の章の結末を一つに固定せず、リツを永久の乗組員とも決めていません。</p><p><a href="https://tales.note.com/ai_neko_namake/wwqir8bbskobr" target="_blank" rel="noopener">原作：宇宙船日誌 番外編</a></p><p class="small">第二章は音なし・オフラインでも動きます。保存はこのブラウザー内のみ。別端末との同期はありません。</p>');$('chapterTitle').onclick=()=>{closeModal();showWelcome();};$('restartMenu').onclick=restart;}
function trap(e,layer){if(e.key!=='Tab')return;const f=[...layer.querySelectorAll('button,a,select,input,summary,[tabindex="0"]')].filter(x=>!x.disabled&&!x.hidden);if(!f.length)return;const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
document.addEventListener('keydown',e=>{if(!$('modalLayer').hidden){if(e.key==='Escape'){e.preventDefault();closeModal();}trap(e,$('modalLayer'));return;}if(!$('dialogLayer').hidden){trap(e,$('dialogLayer'));if((e.key==='Enter'||e.key===' ')&&!e.repeat){e.preventDefault();$('next').click();}}});
$('next').onclick=()=>{if(!state||!state.dialog)return;state=G.next(state);save();render();};$('start').onclick=()=>saved?restart():start();$('resume').onclick=resume;$('closeModal').onclick=closeModal;$('journalButton').onclick=journal;$('menuButton').onclick=menu;$('consult').onclick=()=>{if(!state.dialog&&!state.end)apply(G.consult(state));};
$('welcomeCrew').innerHTML='<img src="'+IMG.sp_girl+'" alt=""><img src="'+IMG.sp_ritsu+'" alt="">';$('crew').innerHTML=['sp_girl','sp_mech','sp_cat','sp_ritsu'].map(k=>'<img src="'+IMG[k]+'" alt="">').join('');load();showWelcome();
})();
